<a href="https://colab.research.google.com/github/werowe/HypatiaAcademy/blob/master/pandas/2024_04_09_more_pandas_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Summary of what we did

* read csf file from internet and made dataframe
* changed index to be planet, i.e., something useful and logical
* lookup row by index value, df.lof['Mercury']
* used describe() to get average, max, min, mass

In [2]:
import pandas as pd

file="https://raw.githubusercontent.com/InterImm/dataset-planets-in-solar-system/master/dataset/planets_in_solar_system.csv"
df = pd.read_csv(file)
df

,name,equatorial_diameter,mass,semi_major_axis,orbital_period,inclination_to_suns_equator,orbital_eccentricity,rotation_period,confirmed_moons,axial_tilt,rings,atmosphere
0,Mercury,0.382,0.06,0.39,0.24,3.38,0.206,58.64,0,0.04,no,minimal
1,Venus,0.949,0.82,0.72,0.62,3.86,0.007,−243.02,0,177.36,no,"CO2, N2"
2,Earth,1.000,1.00,1.00,1.00,7.25,0.017,1,1,23.44,no,"N2, O2, Ar"
3,Mars,0.532,0.11,1.52,1.88,5.65,0.093,1.03,2,25.19,no,"CO2, N2, Ar"
4,Jupiter,11.209,317.80,5.20,11.86,6.09,0.048,0.41,79,3.13,yes,"H2, He"
5,Saturn,9.449,95.20,9.54,29.46,5.51,0.054,0.43,82,26.73,yes,"H2, He"
6,Uranus,4.007,14.60,19.22,84.01,6.48,0.047,−0.72,27,97.77,yes,"H2, He, CH4"
7,Neptune,3.883,17.20,30.06,164.80,6.43,0.009,0.67,14,28.32,yes,"H2, He, CH4"

In [3]:
df.set_index(df['name'],inplace=True)

In [4]:
df

,name,equatorial_diameter,mass,semi_major_axis,orbital_period,inclination_to_suns_equator,orbital_eccentricity,rotation_period,confirmed_moons,axial_tilt,rings,atmosphere
name,,,,,,,,,,,,
Mercury,Mercury,0.382,0.06,0.39,0.24,3.38,0.206,58.64,0,0.04,no,minimal
Venus,Venus,0.949,0.82,0.72,0.62,3.86,0.007,−243.02,0,177.36,no,"CO2, N2"
Earth,Earth,1.000,1.00,1.00,1.00,7.25,0.017,1,1,23.44,no,"N2, O2, Ar"
Mars,Mars,0.532,0.11,1.52,1.88,5.65,0.093,1.03,2,25.19,no,"CO2, N2, Ar"
Jupiter,Jupiter,11.209,317.80,5.20,11.86,6.09,0.048,0.41,79,3.13,yes,"H2, He"
Saturn,Saturn,9.449,95.20,9.54,29.46,5.51,0.054,0.43,82,26.73,yes,"H2, He"
Uranus,Uranus,4.007,14.60,19.22,84.01,6.48,0.047,−0.72,27,97.77,yes,"H2, He, CH4"
Neptune,Neptune,3.883,17.20,30.06,164.80,6.43,0.009,0.67,14,28.32,yes,"H2, He, CH4"

In [5]:
df.loc["Mercury"]

name                           Mercury
equatorial_diameter              0.382
mass                              0.06
semi_major_axis                   0.39
orbital_period                    0.24
inclination_to_suns_equator       3.38
orbital_eccentricity             0.206
rotation_period                  58.64
confirmed_moons                      0
axial_tilt                        0.04
rings                               no
atmosphere                     minimal
Name: Mercury, dtype: object

In [6]:
df["mass"].describe()

count      8.000000
mean      55.848750
std      110.594436
min        0.060000
25%        0.642500
50%        7.800000
75%       36.700000
max      317.800000
Name: mass, dtype: float64

In [7]:
df.sort_values(by="mass")

,name,equatorial_diameter,mass,semi_major_axis,orbital_period,inclination_to_suns_equator,orbital_eccentricity,rotation_period,confirmed_moons,axial_tilt,rings,atmosphere
name,,,,,,,,,,,,
Mercury,Mercury,0.382,0.06,0.39,0.24,3.38,0.206,58.64,0,0.04,no,minimal
Mars,Mars,0.532,0.11,1.52,1.88,5.65,0.093,1.03,2,25.19,no,"CO2, N2, Ar"
Venus,Venus,0.949,0.82,0.72,0.62,3.86,0.007,−243.02,0,177.36,no,"CO2, N2"
Earth,Earth,1.000,1.00,1.00,1.00,7.25,0.017,1,1,23.44,no,"N2, O2, Ar"
Uranus,Uranus,4.007,14.60,19.22,84.01,6.48,0.047,−0.72,27,97.77,yes,"H2, He, CH4"
Neptune,Neptune,3.883,17.20,30.06,164.80,6.43,0.009,0.67,14,28.32,yes,"H2, He, CH4"
Saturn,Saturn,9.449,95.20,9.54,29.46,5.51,0.054,0.43,82,26.73,yes,"H2, He"
Jupiter,Jupiter,11.209,317.80,5.20,11.86,6.09,0.048,0.41,79,3.13,yes,"H2, He"

In [13]:
# fix this, how can we list just certain columns: name and mass


# dataframe[series,series]



df[df['name'], df['mass']].sort_values(by="mass")

InvalidIndexError: (name
Mercury    Mercury
Venus        Venus
Earth        Earth
Mars          Mars
Jupiter    Jupiter
Saturn      Saturn
Uranus      Uranus
Neptune    Neptune
Name: name, dtype: object, name
Mercury      0.06
Venus        0.82
Earth        1.00
Mars         0.11
Jupiter    317.80
Saturn      95.20
Uranus      14.60
Neptune     17.20
Name: mass, dtype: float64)

In [9]:
df.columns

Index(['name', 'equatorial_diameter', 'mass', 'semi_major_axis',
       'orbital_period', 'inclination_to_suns_equator', 'orbital_eccentricity',
       'rotation_period', 'confirmed_moons', 'axial_tilt', 'rings',
       'atmosphere'],
      dtype='object')

In [14]:
# Walker

# df.loc means look by rows and columns

# df[series,series] is not valid


df.loc[:, ['name', 'mass']].sort_values(by="mass")

            name    mass
name
Mercury  Mercury    0.06
Mars        Mars    0.11
Venus      Venus    0.82
Earth      Earth    1.00
Uranus    Uranus   14.60
Neptune  Neptune   17.20
Saturn    Saturn   95.20
Jupiter  Jupiter  317.80

In [15]:
# Tamara

# walker's error was:  df[df['name'], df['mass']].sort_values(by="mass")

# so the proper format is dataframe[ [ array of columns ] ]



df[['name', 'mass']].sort_values(by="mass")

            name    mass
name
Mercury  Mercury    0.06
Mars        Mars    0.11
Venus      Venus    0.82
Earth      Earth    1.00
Uranus    Uranus   14.60
Neptune  Neptune   17.20
Saturn    Saturn   95.20
Jupiter  Jupiter  317.80

In [16]:
# Oleksii

df[['name', 'mass']].sort_values(by="mass")

In [18]:
# Anna

# change settings on Mac to not conver single quote to curled quote.  curled quote is Python


''

df[['name', 'mass']]

            name    mass
name
Mercury  Mercury    0.06
Venus      Venus    0.82
Earth      Earth    1.00
Mars        Mars    0.11
Jupiter  Jupiter  317.80
Saturn    Saturn   95.20
Uranus    Uranus   14.60
Neptune  Neptune   17.20

In [17]:
df.loc[df["equatorial_diameter"] <1 ].sort_values(by="mass")

,name,equatorial_diameter,mass,semi_major_axis,orbital_period,inclination_to_suns_equator,orbital_eccentricity,rotation_period,confirmed_moons,axial_tilt,rings,atmosphere
name,,,,,,,,,,,,
Mercury,Mercury,0.382,0.06,0.39,0.24,3.38,0.206,58.64,0,0.04,no,minimal
Mars,Mars,0.532,0.11,1.52,1.88,5.65,0.093,1.03,2,25.19,no,"CO2, N2, Ar"
Venus,Venus,0.949,0.82,0.72,0.62,3.86,0.007,−243.02,0,177.36,no,"CO2, N2"

In [11]:
df["equatorial_diameter"]

name
Mercury     0.382
Venus       0.949
Earth       1.000
Mars        0.532
Jupiter    11.209
Saturn      9.449
Uranus      4.007
Neptune     3.883
Name: equatorial_diameter, dtype: float64

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8 entries, Mercury to Neptune
Data columns (total 12 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   name                         8 non-null      object
 1   equatorial_diameter          8 non-null      float64
 2   mass                         8 non-null      float64
 3   semi_major_axis              8 non-null      float64
 4   orbital_period               8 non-null      float64
 5   inclination_to_suns_equator  8 non-null      float64
 6   orbital_eccentricity         8 non-null      float64
 7   rotation_period              8 non-null      object
 8   confirmed_moons              8 non-null      int64
 9   axial_tilt                   8 non-null      float64
 10  rings                        8 non-null      object
 11  atmosphere                   8 non-null      object
dtypes: float64(7), int64(1), object(4)
memory usage: 1.1+ KB

In [ ]:
# Homework.

# explain what this is doing

# use this book https://pandas.pydata.org/pandas-docs/stable/user_guide/basics.html



df.loc[:, ['name', 'mass']].sort_values(by="mass")